### ISSUE TITLE
Spawn rubber trees in more places

### ISSUE THREAD

**Issue by powercrystals** [powercrystals/MineFactoryReloaded#10]
Jungles, forest/taiga at least

**Comment by PlusPlusPack** [comment]
Yes do this please.

**Comment by ghost** [comment]
You sure, when I was living in a plains biome in my current world, I had no shortage. There was a lot more rubber trees than regular trees infact.

**Comment by AKA-Syenite** [comment]
https://github.com/powercrystals/MineFactoryReloaded/pull/25
