### ISSUE TITLE
[Bug] All machines do not respect event cancellation

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#101]
All the MFR machines do not respect the event.setCancelled(true) flag used by protections mods/plugins intended to deny access to unauthorized players in SMP.

Even though the protection mods properly identify the machines as being unusable, the GUIs for all machines still process to open up and are accessible.

This is using your 1.51 core and version 637 of MFR

**Comment by powercrystals** [comment]
Ok, I'm totally fine with supporting this, but I need a more specific definition of what isn't being respected. What events and where? Forge doesn't document this stuff in a sane way so even figuring out what events exist can be difficult.

**Comment by jalapeno777** [comment]
I'm much more familiar with bukkit than forge so forgive me if I sound like a raving lunatic.

The event in question is the PlayerInteractEvent ...which occurs when a person right clicks on a gui capable block

http://jd.minecraftforge.net/net/minecraftforge/event/entity/player/PlayerInteractEvent.html

within that is an isCanceled() method.

To properly support this, I believe you need to add an if statement to you gui opening code to check for this isCanceled() method to be true.  If it is then skip openning the gui.

Does that make some sense to you or am I on crack?

**Comment by powercrystals** [comment]
This should be at least partially fixed in 756 - I got the machine blocks and the three RedNet components; if there's something I missed, let me know. Close this if it works as you wanted.

**Comment by jalapeno777** [comment]
@powercrystals  Machine blocks still seem accessible.  Tested harvester, fertilizer and deep storage unit...all had the same result where the server indicated the interact event should be cancelled however the gui still opened up.  

This is using your latest versions of both MFR and the powercrystals core.

**Comment by powercrystals** [comment]
Ok, try again with build 773 - apparently cancelling and denying are two different things. Doh.

**Comment by jalapeno777** [comment]
Just tried again with build 784...no change.  Everything is still accessible.

**Comment by powercrystals** [comment]
Ok, I'm mystified then because I set up a test with just:

```
@ForgeSubscribe
public void onBlockActivated(PlayerInteractEvent e)
{
    e.setResult(Result.DENY);
}
```

And I couldn't click on anything and get to a GUI. I guess I'll need set up an MCPC test environment to figure out this one - do you have directions for how to get to the failing state? I don't know how to set up permissions/etc on any of those environments.

**Comment by powercrystals** [comment]
Try 893.

**Comment by powercrystals** [comment]
I haven't heard anything in a while, so I'm going to assume this is fixed - if it isn't, just reopen it.
