### ISSUE TITLE
Can't translate into russian language

### ISSUE THREAD

**Issue by labpaw** [powercrystals/MineFactoryReloaded#105]
Have some problem with translating into russian language. First I took en_US.lang and made a copy, also renamed in ru_RU.lang. Then I translated one word Planter -> "Плантатор". Placed ru_RU.lang into MineFactoryReloaded-2.6.0B1-xxx.jar in lang folder.
An example: MineFactoryReloaded-2.6.0B1-xxx.jar\powercrystals\minefactoryreloaded\lang\ru_RU.lang. Start game but in game word Planter isn't translated. 
 Well, how me translate the mod?

**Comment by crafteverywhere** [comment]
Check line 367 in MineFactoryReloadedCore.java

**Comment by labpaw** [comment]
Thank's again. Full translate later.
