### ISSUE TITLE
[Severe] SMP Crash - java.lang.NoClassDefFoundError: powercrystals/minefactoryreloaded/gui/client/GuiFactoryInventory

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#115]
NoClassDefFoundError occurring periodically using 2.6-744 in SMP.

Very possibly another case of trying to call client side only functions while running as a server.

Full trace here
http://pastebin.com/FGVePtN0

**Comment by powercrystals** [comment]
This should be fixed in 753 and higher - I actually broke this on my own server shortly after you filed this..
