### ISSUE TITLE
Magic Crops is no longer supported

### ISSUE THREAD

**Issue by LDragon** [powercrystals/MineFactoryReloaded#117]
In MFR 2.5.4 (the one in the Toast pack) none of the magic crops are seen by the harvester. Tested glowstone, redstone, explosive, and diamond seeds in the planter. None of them worked. My Set up is literaly just the toast pack with magic crops dropped in. With magic crops 2.0.7.a

**Comment by powercrystals** [comment]
I just tried magical crops 2.0.7a and it worked flawlessly, so I'm not sure what to tell you. Is there anything in the log about errors involving that compat mod?

**Comment by Emys** [comment]
Also, since Magical Crops 2.1.0 is out now, that's what MFR builds 816+ are compatible with.

(2.5.4 should be working fine with 2.0.7a, though. ctrl-f in your forge log for "probably emy's fault")

**Comment by Emys** [comment]
Magical crops compat is updated, so I'm closing this. Lemme know if you have any further problems.
