### ISSUE TITLE
[Bug] [Build 751] Birch + Fertilizer + Planter + Harvester = Invalid State

### ISSUE THREAD

**Issue by thatsIch** [powercrystals/MineFactoryReloaded#119]
![2013-05-19_20 21 52](https://f.cloud.github.com/assets/2210496/523398/686caa92-c0b2-11e2-8094-4f196fe47374.png)
Machines:
- Fertilizer
- Planter 
- Harvester

What happens: Bottom Trunk of a Birch Tree is getting replaced by a sapling or air. Since Birch has specific growth criteria, the whole setup is running into an dead-lock state

**Comment by powercrystals** [comment]
OK, I've sat trying to cause this for a while and I can't do it. Birches for me will even grow into each other, so that state should allow a second one to grow. I don't know what the hell. I'll leave this open, but I'm not sure I can reproduce (and thus fix) the actual issue.

**Comment by thatsIch** [comment]
Maybe now you have some mods which alter growth of vanilla trees ;-)
I am pretty sure, that per default its growth criteria is at least 5x5x6
Since this area is just a 3x3, non other Birch can grow there o_o

I try again in never builds, cant do much else, if you cannot reproduce it

**Comment by powercrystals** [comment]
I don't have much of anything installed in my test world so if that's non-vanilla behavior I'm surprised, but I haven't seen it generating the above failed case either. I'm not sure what to tell you.

**Comment by thatsIch** [comment]
strangly I got 2 trees at once too now.. Somewhat changed haha. I can close it for now but will re-open it if I detect it again.
