### ISSUE TITLE
soul shards

### ISSUE THREAD

**Issue by PlusPlusPack** [powercrystals/MineFactoryReloaded#12]
you can grind up the mobs that spawn via soul cages.

**Comment by amezick** [comment]
To me this is a feature.  The bug is the drops are not what I expect.  I have yet to get a single iron ingot, enchanted iron armor, or any non enchanted armor from ground zombies.  I only get rotten meat and enchanted leather/gold/chain armor.  No EE3 minium shards.  No Steve Cart presents.

**Comment by powercrystals** [comment]
I think that original bug is supposed to say "can't"...

From looking into it, mods like EE3 that register mob drops (minium shards) do it by listening for mobs getting killed by the player and then just placing their item on the ground. This is impossible for me to intercept in a general fashion so I'm going to have to fix THAT one on a per-mod basis.
