### ISSUE TITLE
RedNet cable-only mode can lead to rednet network confusion and corruption.

### ISSUE THREAD

**Issue by KirinDave** [powercrystals/MineFactoryReloaded#127]
While filming a video (http://www.youtube.com/watch?v=zURlcYvDTek) I found I could reproduce a variety of problems with these steps:
1. Lay down a glowstone lamp, connect it with a length 2 piece of rednet cable to a switch placed on the ground.
2. Turn on the switch.
3. Change the cable to cable-only connect mode.

When done in this order I observed that the glowstone lamp remained on and nothing could turn it off. Further, modestly complex networks where this behavior is triggered would frequently perform stragely, losing all internal state (rednet meter would show 0 on all channels) and require that all cable pieces be broken and a new network be laid down to resume normal operation.

I have some video outtakes  of this bug in aciton if you'd like to see it in action. I reproduced it with a few builds around the 811 mark. 

My workaround was to make sure NO signals were active on the rednet network while changing connections modes. With this taken into consideration I did not encounter unexpected behavior, but this is probably not a practical strategy in a survival game.

**Comment by powercrystals** [comment]
This should be fixed in 822, but let me know if anything's still weird.

**Comment by powercrystals** [comment]
Closing due to no negative feedback. If something's still messed up, open a new issue.
