### ISSUE TITLE
[Question] Compat Mods

### ISSUE THREAD

**Issue by thatsIch** [powercrystals/MineFactoryReloaded#134]
I wonder how much the Compat Mods affect the loading time of the minecraft client? I seem to have 400% more than I even need (since I dont even have some of the mods installed)

If it _is_ effecting it, would you be able to add a config option to not load some compat helpers?

I just wondered by seeing all the compat helpers in the ModList Button on the startscreen of the client.

**Comment by powercrystals** [comment]
You cannot tell a mod to not load in FML, but the ones who are missing their partner mods do not do anything at all, so the impact should be very small. If you really don't want them anyway you can just delete them out of the jar.
