### ISSUE TITLE
Rednet Historian Rendering Bug

### ISSUE THREAD

**Issue by ghost** [powercrystals/MineFactoryReloaded#137]
This rendering bug seems to happen randomly at any time.
http://imgur.com/q8x8B1B

**Comment by powercrystals** [comment]
I have no idea how that happened but that's hilarious. I can't fix it until there's a reproducible case though.

**Comment by ghost** [comment]
I'll go see if I can find something that is causing it. It is still happening a lot for me. Could it be because I am in mcp using deobfuscated code?

**Comment by powercrystals** [comment]
Should be fixed now
