### ISSUE TITLE
Support for Natura & Tinker's Construct crops

### ISSUE THREAD

**Issue by KirinDave** [powercrystals/MineFactoryReloaded#147]
Tinker's construct adds a variety of really useful crops including a good replacement for the loss of Redpower2's flax (cotton) and metallic berries for harvesting. It would be really swell if the harvester and planter could work with these. As of 2.6.1B1-882 they do not appear to.

**Comment by Leftorius** [comment]
there was a change so when I'm right, Natura & TC will support MFR on their side so power crystals removed the abilitiy on his side. Just wait for the new release (Or I'm wrong).

**Comment by powercrystals** [comment]
Correct, it's on mDiyo's side now.

**Comment by KirinDave** [comment]
We are taking pretty close to current on Natura's dev releases. I know a
recent change accommodated golems.
