### ISSUE TITLE
Minefractory Reloaded Crashes new ICBM

### ISSUE THREAD

**Issue by Rinelw** [powercrystals/MineFactoryReloaded#149]
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 04.06.13 21:17
Description: Exception in server tick loop

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: universalelectricity.prefab.multiblock.BlockMulti.setChannel(Ljava/lang/String;)Luniversalelectricity/prefab/multiblock/BlockMulti;
at cpw.mods.fml.common.LoadController.transition(LoadController.java:142)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:515)
at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:85)
at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:350)
at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:94)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:578)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)
Caused by: java.lang.NoSuchMethodError: universalelectricity.prefab.multiblock.BlockMulti.setChannel(Ljava/lang/String;)Luniversalelectricity/prefab/multiblock/BlockMulti;
at icbm.core.ZhuYaoBase.preInit(ZhuYaoBase.java:132)
at icbm.wanyi.ZhuYaoWanYi.preInit(ZhuYaoWanYi.java:65)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:494)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:165)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
at com.google.common.eventbus.EventBus.post(EventBus.java:267)
at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:98)
at cpw.mods.fml.common.Loader.loadMods(Loader.java:514)
... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
Minecraft Version: 1.5.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.7.0_21, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1009682632 bytes (962 MB) / 1362952192 bytes (1299 MB) up to 1908932608 bytes (1820 MB)
JVM Flags: 2 total; -Xmx2G -Xms1G
AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Suspicious classes: FML and Forge are installed
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
CraftBukkit Information: 
Running: 
Failed to handle CraftCrashReport:
java.lang.NullPointerException
at org.bukkit.Bukkit.getName(Bukkit.java:69)
at org.bukkit.craftbukkit.v1_5_R3.CraftCrashReport.call(CraftCrashReport.java:19)
at net.minecraft.crash.CrashReportCategory.func_71500_a(CrashReportCategory.java:106)
at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:59)
at net.minecraft.crash.CrashReport.(CrashReport.java:41)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:635)
at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:573)

FML: MCP v7.51 FML v5.2.12.712 Minecraft Forge 7.8.0.712 75 mods loaded, 75 mods active
mcp{7.44} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized
FML{5.2.12.712} [Forge Mod Loader](coremods) Unloaded->Constructed->Pre-initialized
Forge{7.8.0.712} [Minecraft Forge](coremods) Unloaded->Constructed->Pre-initialized
CodeChickenCore{0.8.6.6} [CodeChicken Core](coremods) Unloaded->Constructed->Pre-initialized
CoFHCore{1.5.2.2} [CoFH Core](coremods) Unloaded->Constructed->Pre-initialized
ImmibisMicroblocks{55.0.1} [Immibis's Microblocks](coremods) Unloaded->Constructed->Pre-initialized
NotEnoughItems{1.5.2.13} [Not Enough Items](coremods) Unloaded->Constructed->Pre-initialized
PowerCrystalsCore{1.1.6} [PowerCrystals Core](coremods) Unloaded->Constructed->Pre-initialized
mod_bspkrsCore{v2.04(1.5.2)} [bspkrsCore]([1.5.2]bspkrsCorev2.04.zip) Unloaded->Constructed->Pre-initialized
TreeCapitator{Forge 1.5.2.r01} [TreeCapitator]([1.5.2]TreeCapitator.Forge.1.5.2.r01.Uni.CoreMod.jar) Unloaded->Constructed->Pre-initialized
CoFHNetwork{1.5.2.2} [CoFHNetwork](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized
CoFHWorld{1.5.2.2} [CoFHWorld](CoFHCore-1.5.2.2.jar) Unloaded->Constructed->Pre-initialized
ImmibisMicroblocksInstallCheck{55.0.1} [Immibis's Microblocks (Check for incorrect installation)](immibis-microblocks-55.0.1.jar) Unloaded->Constructed->Pre-initialized
DamageIndicatorsMod{2.7.0.1} [Damage Indicators](1.5.2 DamageIndicators v2.7.0.1.zip) Unloaded->Constructed->Pre-initialized
WeepingAngelsMod{1.5.10} [Weeping Angels Mod](152-1510WeepingAngels.zip) Unloaded->Constructed->Pre-initialized
BuildCraft|Core{3.6.0} [BuildCraft](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
BuildCraft|Factory{3.6.0} [BC Factory](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
BuildCraft|Transport{3.6.0} [BC Transport](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
BuildCraft|Silicon{3.6.0} [BC Silicon](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
APUnofficial{2.3.0} [Additional Pipes](AdditionalPipes2.3.0-BC3.5.3.jar) Unloaded->Constructed->Pre-initialized
ThermalExpansion{2.4.3.0} [Thermal Expansion](ThermalExpansion-2.4.3.0.jar) Unloaded->Constructed->Pre-initialized
IC2{1.115.334-lf} [IndustrialCraft 2](industrialcraft-2_1.115.334-lf.jar) Unloaded->Constructed->Pre-initialized
AdvancedMachines{4.9} [IC2 Advanced Machines Addon](AdvancedMachines_1.5.2.zip) Unloaded->Constructed->Pre-initialized
AdvancedPowerManagement{1.2.68-IC2-1.115} [Advanced Power Management](AdvancedPowerManagement-1.2.68-IC2-1.115.jar) Unloaded->Constructed->Pre-initialized
BuildCraft|Builders{3.6.0} [BC Builders](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
BuildCraft|Energy{3.6.0} [BC Energy](buildcraft-A-3.6.0.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded{1.5.1R2.6.0B1} [MineFactory Reloaded](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
AppliedEnergistics{rv.10.m} [Applied Energistics](appeng-rv10-m.zip) Unloaded->Constructed->Pre-initialized
AtomicScience{0.5.3} [Atomic Science](Atomic_Science_v0.5.3.51.jar) Unloaded->Constructed->Pre-initialized
BiomesOPlenty{0.5.4} [Biomes O' Plenty](Biomes-O-Plenty-0.5.4-R3.zip) Unloaded->Constructed->Pre-initialized
ComputerCraft{1.53} [ComputerCraft](ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized
CCTurtle{1.53} [ComputerCraft Turtles](ComputerCraft1.53.zip) Unloaded->Constructed->Pre-initialized
DimensionalDoors{1.5.2R1.3.6RC1} [Dimensional Doors](DimensionalDoors-1.5.2R1.3.6RC1-71.zip) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatForestryPre{1.5.1R2.6.0B1} [MFR Compat: Forestry (2)](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
Forestry{2.2.6.0} [Forestry for Minecraft](forestry-A-2.2.6.0.jar) Unloaded->Constructed->Pre-initialized
GregsLighting{1.5.1R1.8.1} [Greg's Lighting](GregsLighting-1.8.1-7.jar) Unloaded->Constructed->Pre-initialized
ICBM|Contraption{1.2.0} [ICBM|Contraption](ICBM_Contraption_v1.2.0.116.jar) Unloaded->Constructed->Errored
ICBM|Sentry{1.2.0} [ICBM|Sentry](ICBM_Sentry_v1.2.0.116.jar) Unloaded->Constructed->Errored
ICBM|Explosion{1.2.0} [ICBM|Explosion](ICBM_Explosion_v1.2.0.116.jar) Unloaded->Constructed->Errored
iChunUtil{1.0.1} [iChunUtil](iChunUtil1.0.1.zip) Unloaded->Constructed->Pre-initialized
ImmibisCore{55.1.1} [Immibis Core](immibis-core-55.1.1.jar) Unloaded->Constructed->Pre-initialized
inventorytweaks{1.55-dev} [Inventory Tweaks](InventoryTweaks-1.55-dev-b22.jar) Unloaded->Constructed->Pre-initialized
IronChest{5.2.6.412} [Iron Chest](ironchest-universal-1.5.2-5.2.6.412.zip) Unloaded->Constructed->Pre-initialized
PortalGun{1.5.2} [PortalGun](PortalGun1.5.2.zip) Unloaded->Constructed->Pre-initialized
Thaumcraft{3.0.5e} [Thaumcraft](Thaumcraft3.0.5e.zip) Unloaded->Constructed->Pre-initialized
KBITC3EssenceAddon{2.3.2} [ThaumCraft3 Essence Addons](KBI TC3 Essentia Everything Addon for 1.5.1.zip) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatAppliedEnergistics{1.5.1R2.6.0B1} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatAtum{1.5.1R2.6.0B1} [MFR Compat: Atum](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatBackTools{1.5.1R2.6.0B1} [MFR Compat: BackTools](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatBiomesOPlenty{1.5.1R2.6.0B1} [MFR Compat: Biomes O' Plenty](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatChococraft{1.5.1R2.6.0B1} [MFR Compat: Chococraft](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatExtraBiomes{1.5.1R2.6.0B1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatForestry{1.5.1R2.6.0B1} [MFR Compat: Forestry](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatIC2{1.5.1R2.6.0B1} [MFR Compat: IC2](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatMagicalCrops{1.5.1R2.6.0B1} [MFR Compat: Magical Crops](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatNatura{1.5.1R2.6.0B1} [MFR Compat: Natura](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatPams{1.5.1R2.6.0B1} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatRP2{1.5.1R2.6.0B1} [MFR Compat: RP2](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatSoulShards{1.5.1R2.6.0B1} [MFR Compat: SoulShards](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatSufficientBiomes{1.5.1R2.6.0B1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MFReloaded|CompatThaumcraft{1.5.1R2.6.0B1} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatThermalExpansion{1.5.1R2.6.0B1} [MFR Compat: ThermalExpansion](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatTConstruct{1.5.1R2.6.0B1} [MFR Compat: TConstruct](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatTwilightForest{1.5.1R2.6.0B1} [MFR Compat: TwilightForest](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatVanilla{1.5.1R2.6.0B1} [MFR Compat: Vanilla](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
MineFactoryReloaded|CompatXyCraft{1.5.1R2.6.0B1} [MFR Compat: XyCraft](MineFactoryReloaded-2.6.0B1-759.jar) Unloaded->Constructed->Pre-initialized
NEIPlugins{1.0.8.7} [NEI Plugins](NEIPlugins-1.0.8.7.jar) Unloaded->Constructed->Pre-initialized
NetherOres{1.5.1R2.1.3} [Nether Ores](NetherOres-2.1.3-60.jar) Unloaded->Constructed->Pre-initialized
OCS{0.1.5i} [OpenCCSensors](OpenCCSensors-0.1.5i.jar) Unloaded->Constructed->Pre-initialized
PowerConverters{1.5.1R2.3.0} [Power Converters](PowerConverters-2.3.0-55.jar) Unloaded->Constructed->Pre-initialized
RopesPlus{1.4.0} [Ropes+](RopePlus_1.5.2.zip) Unloaded->Constructed->Pre-initialized
secretroomsmod{4.6.0} [SecretRoomsMod](SecretRoomsMod-universal-4.6.0.280.zip) Unloaded->Constructed->Pre-initialized
Tubestuff{55.0.1} [Tubestuff](tubestuff-55.0.1.jar) Unloaded->Constructed->Pre-initialized
UsefulFood{1.4.2} [UsefulFood](UsefulFood-1.5.1_1.4.2-universal.zip) Unloaded->Constructed->Pre-initialized
WildCaves3{0.4.2} [Wild Caves 3](WildCaves3-0.4.2.zip) Unloaded->Constructed->Pre-initialized
Profiler Position: N/A (disabled)
Is Modded: Definitely; Server brand changed to 'mcpc,craftbukkit,fml,forge'
Type: Dedicated Server (map_server.txt)

**Comment by powercrystals** [comment]
Update your MFR - we stopped packaging the prefab folder some time ago.
