### ISSUE TITLE
PRC Delay (8-Channel) is strange.

### ISSUE THREAD

**Issue by stranger1029** [powercrystals/MineFactoryReloaded#153]
I study the Programmable RedNet Controller logics from source code.
and I see some strange code.

in Delay8ch.java
Output port is only 1. but real output is array int[8] in source code.
(I can't check in the game, only see the source code)

**Comment by powercrystals** [comment]
That's what I get for programming while sleep deprived. Thanks, I'll fix that tomorrow.
