### ISSUE TITLE
Q: How should I encode a lang file?

### ISSUE THREAD

**Issue by ghost** [powercrystals/MineFactoryReloaded#157]

**Comment by powercrystals** [comment]
I don't even understand the question. There's a whole bunch of existing files you can use as a reference anyway.

**Comment by ghost** [comment]
I assume you're accepting localization files? I was going to make a sr_RS.lang file, and I noticed the other lang files had stuff like \u64ad\u79cd\u673a, so I assumed they are not encoded in UTF-8. I didn't see any issues explaining how I should encode a localization file, and that's what I asked you.

**Comment by powercrystals** [comment]
The spanish ones are entered directly, the russian and chinese ones are done that way. I have to admit I have no idea why this is the case - you might have to just try it and see what works, or maybe try asking one of the other people who contribute the localizations what their reasoning is.

Then again I recall the guy doing the spanish ones having issues so maybe the unicode escape sequences are required.

But I will accept any localizations offered.

**Comment by powercrystals** [comment]
Closing as answered.

**Comment by ghost** [comment]
Sorry for this post-answer but I think they should be encoded with ISO 8859-1

**Comment by powercrystals** [comment]
UTF-8, actually. That would work too, but it should be UTF-8. The standard way of doing it is usually to explicitly enter any UTF-8 chars as \uXXXX for maximum compatibility, but it's not strictly necessary.

**Comment by ghost** [comment]
Ok. I just thought it's ISO 8859-1 because in some other projects (like in BuildCraft) they has to be ISO 8859-1. I thought it's Minecraft standard or something
