### ISSUE TITLE
Add option to allow custom mods wood and leaves type

### ISSUE THREAD

**Issue by zlepper** [powercrystals/MineFactoryReloaded#170]
This support could be given by a config option where it would be possible to list the ids of the block the havester fx can "dig" the blocks mentioned in the config, incase of special wood.

**Comment by powercrystals** [comment]
This won't happen because there's a lot of weird edge cases that require special programming. A config option would cover some cases, but then I'd get asked to support the rest, and that's just not feasible. I'm sorry.
