### ISSUE TITLE
RedNet cables perpetually sustain signals in redstone dust

### ISSUE THREAD

**Issue by unpairedbracket** [powercrystals/MineFactoryReloaded#178]
If cables and redstone dust are placed in either dust-dust-cable or cable-dust-cable order and power either of the ends (but not the wire in the middle), the signal remains once the power is removed.
Initial situation:
![2013-06-10_22 28 04](https://f.cloud.github.com/assets/543022/634298/25f9ff82-d216-11e2-8b10-02a8aecc44aa.png)

Powered:
![2013-06-10_22 28 11](https://f.cloud.github.com/assets/543022/634303/34c50ed0-d216-11e2-939b-62d95024240b.png)

(Should be) unpowered:
![2013-06-10_22 28 20](https://f.cloud.github.com/assets/543022/634307/37409e36-d216-11e2-9398-c8b5ba589637.png)

Removing any of the 3 conducting blocks causes the signal to drop as it should, as does placing a repeater so that the dust in the middle conducts into the repeater, or powering, then unpowering the dust in the middle.

I'd be surprised if nobody had run into this before, but I couldn't find the same issue anywhere by searching. #127 seems similar, maybe it's related?

**Comment by powercrystals** [comment]
Man, I thought I fixed this one. Thanks for bringing it to my attention.

**Comment by unpairedbracket** [comment]
I'd initially seen this in 924, which I thought was the latest, but I've just found the Jenkins builds and it's also present in 943

**Comment by powercrystals** [comment]
Fixed it (947). Now they lose power slowly but it's better than nothing; I don't think I can fix that without rewriting redstone dust and I really don't want to do that.
