### ISSUE TITLE
Suggestion: Connected textures for stained glass

### ISSUE THREAD

**Issue by immibis** [powercrystals/MineFactoryReloaded#186]
Or just remove the the grey borders.

A stained glass window with borders: http://puu.sh/3ewCD.jpg
The same window without borders: http://puu.sh/3ewKN.jpg

**Comment by Leftorius** [comment]
Yay, without the borders that glass looks really nice :) so a connected texture thingy would be cool

**Comment by immibis** [comment]
Wrong issue number?
