### ISSUE TITLE
PRC doesn't render correctly

### ISSUE THREAD

**Issue by LordS3B** [powercrystals/MineFactoryReloaded#197]
Hello, have an error to report:

The Programmable RedNet Controller doesn't render correctly, it renders all white, with only the model, look:

![2013-06-18_12 53 20](https://f.cloud.github.com/assets/4141587/670305/5b1503bc-d840-11e2-80c1-c051e68d7aad.png)

I don't know if it has something to do with LWJGL, or Java or qith my graphics card. I'm not using optifine. Help

**Comment by powercrystals** [comment]
I uh.. what the hell? If you open the jar and look at \powercrystals\minefactoryreloaded\textures\tileentity\redcomp.png is it correct (well, it'll look weird if you aren't used to UV-mapped textures, but is not solid white)? What version of MFR/PCC/Forge/MC? What kind of hardware are you using?

**Comment by LordS3B** [comment]
I have Intel Integrated Graphics, Intel Pentium 4 Dual Core 2.6 GHz, with Minecraft 1.5.2, forge #750, PCC 1.1.6-17 and MFR 2.6.2, LWJGL 2.9.0. And this also happens with the MPS tinker table and lux capacitor.

**Comment by powercrystals** [comment]
If it happens with those too it must be some weird openGL issue with your graphics card (a P4 is gonna have a pretty old GPU). I don't know what to tell you, but I'm definitely not going to be able to fix it so I'm sadly going to have to close this.
