### ISSUE TITLE
what is the needle gun?

### ISSUE THREAD

**Issue by stranger1029** [powercrystals/MineFactoryReloaded#215]
i try to translate word. but, i can't choose word 'needlegun'.
'shot a needle' from word. 'old style rifle' from dictionary.
what is your intention?

**Comment by powercrystals** [comment]
Uh, basically, 'gun' refers to the fact that it is well, a gun ('rifle' may be closer to the intended meaning), and 'needle' refers to it firing very small needle-like projectiles.
