### ISSUE TITLE
They Seem To Float Bug See The Picture

### ISSUE THREAD

**Issue by GnomesStalkChildren** [powercrystals/MineFactoryReloaded#216]
![2013-06-22_18 18 01](https://f.cloud.github.com/assets/2353983/691478/0049b354-db8a-11e2-8334-eedf9da28709.png)

**Comment by GnomesStalkChildren** [comment]
i have  tryed and i moved the spawn on the mystcraft book up 1 so they would land properly but didnt work still a floating alein

**Comment by powercrystals** [comment]
This can't really be fixed in the general case. I'll keep it in mind for the future, but don't expect anything anytime soon. In the meantime, consider that a side effect of the advanced space-conveyor technology causing them to float through the air with ease for reduced friction. Or something.

**Comment by GnomesStalkChildren** [comment]
ok i will and aweosome i have alein witches
