### ISSUE TITLE
Mods that register preferred ore for laser focus effect can override existing ones.

### ISSUE THREAD

**Issue by Zjarek** [powercrystals/MineFactoryReloaded#230]
When other mod add laser drill focus that is the same as existing one, for example copper ore as red, then it gets overridden. TE register copper ore for red focus, so you can't focus drill on redstone ore.

Overall there is maximum only one preferred ore per focus, which could cause problems if more mods would add their ores, 16 colors isn't that much.

**Comment by powercrystals** [comment]
This is something I've been meaning to fix but haven't gotten around to doing yet - I'm going to make the per-color preferences a list internally.

**Comment by Emys** [comment]
Oh, didn't realize this was on the issues list. It's done.
