### ISSUE TITLE
Steve's Carts 2 Items Display Improperly with MFR

### ISSUE THREAD

**Issue by Bovive** [powercrystals/MineFactoryReloaded#231]
![java 2013-06-27 13-43-41-98](https://f.cloud.github.com/assets/4776549/718051/99a6ee26-df5a-11e2-965c-f43db821bdf8.png)

Starting with build 1021 (which fixed a crash associated with MFR and SC2 in NEI), some of the Steve's Carts 2 components show up with an incorrect name and/or image. This occurs both in NEI and in item/inventory form. Attached is a screenshot demonstrating this. With MFR removed, the items show up normally.

**Comment by Emys** [comment]
I'd say item ID conflict, but I can't be sure, might want to check your configs. What ID range are MFR and SC2 using?

Also which build of SC2 are you using, so I can try to reproduce it?

**Comment by Bovive** [comment]
Thanks Emys, the item ID conflict is exactly what it was. I feel ashamed not thinking of that. Thanks again, I truly appreciate your help!
