### ISSUE TITLE
D-Latch (Clocked) rename to D-Flipflop

### ISSUE THREAD

**Issue by stranger1029** [powercrystals/MineFactoryReloaded#239]
flipflop is clocked(edge trigger) version of latch.
so, i think D-Latch (Clocked) is D-Flipflop.

**Comment by powercrystals** [comment]
D-Latch sets value to input value on rising edge of clock.
Flip-flop inverts its value on rising edge of clock if input is nonzero.

They are not the same thing.

**Comment by stranger1029** [comment]
flip-flop of invert value is T-FlipFlop(Toggle-FlipFlop).
D-FlipFlop is set to D value like D-Latch.

**Comment by powercrystals** [comment]
It's not a true D-FlipFlop either because it doesn't have S or R inputs. I guess I could add them, but that seems weird. I'll have to think about what I want to do here.

**Comment by stranger1029** [comment]
return to first... clocked latch is flip-flop.
so i think change the word "latch" is need.
