### ISSUE TITLE
1075 - All old DSUs are invalidated

### ISSUE THREAD

**Issue by henryzhangsta** [powercrystals/MineFactoryReloaded#270]
Any DSUs placed before 1075 have their internal inventories set to 0 and are unable to accept any more items except the first stack until emptied, broken, and replaced. Breaking and replacing with items still inside does not fix the problem.

**Comment by Emys** [comment]
welp. It looks like part of this is a display bug, and part of it is a loading failure. I'll see if I can sort it out later today.
