### ISSUE TITLE
[Request] Configurable mob detection levels from grinder and slaughterhouse

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#271]
In the same manner a breeder will stop working if the # of entities in an area gets too high I would love to see grinders and slaughterhouses have a reverse setup in which they'll only work if a # of entities amount is at a certain level.

Ideally this would be configurable on a per block level so a player could automate a breeder & grinder/slaughterhouse setup to allow for building up to a certain # of animals and then killing them until population gets to a particular limit to avoid completely wiping out the area and allowing for repopulation.

**Comment by powercrystals** [comment]
You saw I added a mob counting machine yesterday, right? (Beware build 1075 though)

**Comment by jalapeno777** [comment]
Ahh, I completely missed that...will need to give it a look.  Thanks for pointing it out
