### ISSUE TITLE
quick and dirty update for minecraft 1.6.2

### ISSUE THREAD

**Issue by stranger1029** [powercrystals/MineFactoryReloaded#283]
https://github.com/stranger1029/MineFactoryReloaded
https://github.com/stranger1029/PowerCrystalsCore

removed BC, UE dependency. (no have api)
replaced to fluids from liquids.
removed WorldProxy and Grinder update. (need hard works)
moved all resources to /assets.
and some fixed for minecraft/forge 1.6.2.

tested with IC2 1.118.400-lf.

**Comment by powercrystals** [comment]
Emy, do not merge this without talking to me first.
