### ISSUE TITLE
Multipart Rednet Placing issue

### ISSUE THREAD

**Issue by t3chguy** [powercrystals/MineFactoryReloaded#318]
if you attempt to place a redstone torch or lever [maybe more] directly onto an MFR Rednet Cable you get the following crash: http://pastebin.com/Z1WVaJwN
I guess it has something to do with Forge Multipart allowing those two objects to be placed multiple times within the same 1^3 block space.

**Comment by skyboy** [comment]
This is not a MFR bug, this is a Multipart bug.

**Comment by allout58** [comment]
I have had the same problem. Here is another crash log if it will help: http://pastebin.com/f8VaHfqL.

**Comment by t3chguy** [comment]
@allout58 It's fixed in later versions of MultiPart ;)

**Comment by allout58** [comment]
Thanks, I found that out after some research...
