### ISSUE TITLE
harvester crash server

### ISSUE THREAD

**Issue by ghost** [powercrystals/MineFactoryReloaded#363]
at some circumstates harvester can crash server:

http://pastebin.com/3KZBdWgQ

MFR 2.7.5

**Comment by marcin212** [comment]
Profiler:
https://dl.dropboxusercontent.com/u/25172450/bugs/znssud.jpg

setup without harvester
http://ubuntuone.com/4PKdpVeVsoCGmDKvkfHKQP

**Comment by ghost** [comment]
fixed in skyboy branch
