### ISSUE TITLE
TC + MFR in DW20 pack: 2000 Vacuos for scanning DSU

### ISSUE THREAD

**Issue by eslachance** [powercrystals/MineFactoryReloaded#365]
Wow, the abbreviations in the title >.<

So the issue is that scanning Deep Storage Units (had a stack of 4 on the floor as dropped items) gives a whooping, unbelievable 2000 research points in Vacuos. Yeouch!

From the looks of my issue being closed on the TC side with "Blame the MFR people", I'm guessing research points are attributed in each mod individually...

Ref: https://github.com/Azanor/thaumcraft/issues/600

**Comment by skyboy** [comment]
Yeah, it's intentional. It can hold 2 billion of any given item; it has to be quite empty to do that.

**Comment by eslachance** [comment]
Hum. I dunno I would expect something in the lines of 20, 30 vacuos and maybe 6 alienis for the ender eyes? Perhaps something about technology too, since mfr is mostly tech after all...

**Comment by eslachance** [comment]
Hm. I guess issues here aren't ever closed >.<
