### ISSUE TITLE
Animal duping bug with mo'creatures

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#37]
If the safari net is used on a mo'creatures tamed animal.  The safari net fills with the animal entity but it does not despawn the original animal.

This allows for unlimited duping of animals on SMP servers bypassing restrictions on # of allowed tamed animals and adding mass amounts of entities on chunks.

Theoretically a malicious person creatively could use deployers or other automated devices to use this flaw to cripple a server.

**Comment by powercrystals** [comment]
Are you on the latest version? 2.1.4 fixed a lot of things that were wrong with the Safari Net including the most likely cause for this.

**Comment by jalapeno777** [comment]
We are running on version 2.1.4.  There are a few other mod based issues with the net we're still seeing as well but nothing as major as the tamed animal duping.

**Comment by powercrystals** [comment]
Can you give me an exact set of steps to test this, starting with "spawn X mob"? And which version of mo creatures? Standard server or MCPC or equivalent?

**Comment by jalapeno777** [comment]
MCPC+ Build 203 (although every version still seems to cause this)
Mo'Creatures 4.5.1 (using the MCPC+ specific version at http://www.mcportcentral.co.za/index.php?topic=4657.0)

Spawn or locate a horse
Feed it enough apples to tame it
Name it
Put safari net in inventory
Right click on tamed horse with safari net in hand
Horse will remain where it is, safari net now filled with "Horse"
With safari net still in hand, right click on ground anywhere
New horse spawns.  Has same features as original horse (tamed, same name as what was issued, etc)
Rinse & Repeat to spawn more horses

This only occurs with tamed animals.  Untamed animals despawn as intended when captured with a net

**Comment by powercrystals** [comment]
I'm willing to bet this is a problem with how MCPC+ works - I suspect it's denying me the ability to 'kill' the mob since it's tamed. I'm not immediately sure what to do about this, but I will definitely take a look at it and see if I can detect that failure. Thanks!

**Comment by powercrystals** [comment]
I've been unable to get an MCPC version to actually work - using MoCreatures just causes me to crash as soon as I login. Would you be able to try the beta build at http://build.technicpack.net/job/MineFactoryReloaded/247/ and see if it works for you? It should print a message to chat indicating failure.

**Comment by powercrystals** [comment]
Er, scratch that, the chat message almost certainly won't work (which is why I call it a beta...). But it should still fail to fill the net at least.

**Comment by jalapeno777** [comment]
I'll give it a shot and let you know

**Comment by jalapeno777** [comment]
I got around to testing this today.  No chat message (as you hinted at)...it did prevent the tamed animal from being taken BUT it also crashed the server:

http://pastebin.com/xYkXefxt

This was using the 247 build.  I'll give the 273 build a shot in case you've improved things since.

**Comment by jalapeno777** [comment]
#273 seems to have resolved the crashing issue and maintains the preventing of netting tamed animals.  Nice work =)

**Comment by powercrystals** [comment]
Thanks!
