### ISSUE TITLE
(1.7.10) No support for MagicalCrops

### ISSUE THREAD

**Issue by xzereha** [powercrystals/MineFactoryReloaded#386]
In 1.7.10 the ability to plant and harvest MagicalCrops or any mod crops at all. Is this is issue or is that feature being dropped?

**Comment by rfox90** [comment]
https://github.com/skyboy/MineFactoryReloaded is the 1.7.10 version.

try searching: https://github.com/skyboy/MineFactoryReloaded/search?utf8=%E2%9C%93&q=crops&type=Issues
