### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by neclimdul** [powercrystals/MineFactoryReloaded#400]
It would be nice to have a license associated with the code so if someone wants to help they know what terms they can contribute under.

Github has some great information about licensing in their help.
https://help.github.com/articles/open-source-licensing/

**Comment by vmrob** [comment]
Please see #341.

> Though I'm not exactly active anymore I still get notifications from this tracker (and then immediately ignore them), so congratulations on successfully if perhaps inadvertently contacting me. For your actual question, the MIT license would be fine by me. I am not going to do any further commits one way or the other though so as to avoid giving people hope that I'm returning, so hopefully this comment is sufficient because there will never be a LICENSE or README in any of these repositories. If not, uh, oh well?
