### ISSUE TITLE
Vanilla Ice Issue

### ISSUE THREAD

**Issue by RyuDragonRyder** [powercrystals/MineFactoryReloaded#41]
[INFO] [STDOUT] CONFLICT @ -154 item slot already occupied by vq@378b29ff while adding vq@117240d6
[INFO] [fml.ItemTracker] The mod MFReloaded is overwriting existing item at 102 (amp from Minecraft) with vq

[INFO] [STDOUT] CONFLICT @ -177 item slot already occupied by vq@5ca2aea while adding powercrystals.minefactoryreloaded.decorative.ItemBlockVanillaIce@1bc76b9e
[INFO] [fml.ItemTracker] The mod MFReloaded is overwriting existing item at 79 (akr from Minecraft) with powercrystals.minefactoryreloaded.decorative.ItemBlockVanillaIce

this keeps happening over and over, and no idea why on the conflict.

**Comment by powercrystals** [comment]
Fixed the CONFLICT @ lines. The rest of it is totally normal since I am in fact overwriting vanilla items. Thanks!

**Comment by ipatrol** [comment]
Needs to be reopened, because overwriting the vanilla ice (he he, "vanilla ice") causes MASSIVE problems with the recipes for IC2 experimental, Thermal Expansion, NEI, and other mods.

**Comment by rfox90** [comment]
No, write another issue. Nothing to do with original problem.
