### ISSUE TITLE
Enhancement Request: Sticky items on conveyors

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#42]
The one thing that stops myself and all the other players on our SMP server from effectively using conveyors is the fact the items are not sticky.  Anyone that gets close enough can draw items off the conveyor into their inventory.

A wonderful addition would be an option to make items sticky on the conveyors forcing them to remain on the belt unless the belt ends or the item is taken by an appropriate machine (router, collector, etc)

**Comment by powercrystals** [comment]
This seems easy enough.

**Comment by powercrystals** [comment]
And done. Items on conveyors can't be picked up; there's a 2s delay after they run off the end before you can grab them.
