### ISSUE TITLE
[Feature Request] Laser Drill Foci change color of laser

### ISSUE THREAD

**Issue by gr8pefish** [powercrystals/MineFactoryReloaded#423]
A neat aesthetic enhancement might be to have the different color laser foci in a laser drill change the color of the beam of energy that is rendered in game. Just a thought, implement if you want.

**Comment by WolfieWaffle** [comment]
I support this, that would be really cool.

**Comment by TheJulianJES** [comment]
This is the wrong bugtracker. https://github.com/skyboy/MineFactoryReloaded/issues is the right bugtracker.
