### ISSUE TITLE
RedNet Problem 

### ISSUE THREAD

**Issue by hasezoey** [powercrystals/MineFactoryReloaded#432]
Crash Log: http://pastebin.com/jGyUWQgZ

RedNet Cable Problem? I Play on FTB Infinity.

Please Fix it :)

**Comment by rfox90** [comment]
Wrong repo use https://github.com/skyboy/MineFactoryReloaded

**Comment by hasezoey** [comment]
oh sorry :) false mod?

(Sorry I'm German)

**Comment by rfox90** [comment]
skyboy took over development from powercystals awhile ago. Or something like that

**Comment by hasezoey** [comment]
oh sorry :) i have searcht an no looked xD Thanks
