### ISSUE TITLE
MineFactoryReloaded-[1.10.2]2.9.0B1-226 causing startup crash.

### ISSUE THREAD

**Issue by border999** [powercrystals/MineFactoryReloaded#446]
It should be noted that optifine is involved most likely: OptiFine_1.10.2_HD_U_E3
https://pastebin.com/Ap9E2KaF
It's some form of rendering error with the milk bucket.

**Comment by Glease** [comment]
Please go to skyboy's fork for issues. Powercrystals is no longer maintaining this mod. Actually this happened like 3 or 4 years ago. I'm quite surprised that there are still people reporting issues here.

Oh, here is a link to the skyboy's repo in case you failed to find it: http://github.com/skyboy/MineFactoryReloaded/issues

**Comment by powercrystals** [comment]
I'm too lazy to unsubscribe to the issue notices and believe me @Glease I am just as surprised as you are every time this happens :)

**Comment by Glease** [comment]
I don't unwatch repos that don't actually send any notifications. Too lazy to do that too lol.

--- Original Message ---

**Comment by Glease** [comment]
Anyway, we should have a bot that automatically reply my above notice....
