### ISSUE TITLE
Auto-spawner: Not using Mobessence 

### ISSUE THREAD

**Issue by jalapeno777** [powercrystals/MineFactoryReloaded#48]
It seems any non-vanilla mob captured via safari net and used in the autospawner will still use power but will not require ANY mob essence in order to spawn mobs.

This was confirmed with both Mo'creatures (including the modified vanilla creatures) and Witches and more mobs.  It was on a production server so I haven't been able to test if this happens with normal vanilla mobs.

**Comment by powercrystals** [comment]
Fixed in the beta builds. Will be fixed in 2.3 (in a few days).
