### ISSUE TITLE
Rubber Trees not compatible with Treecapitator?

### ISSUE THREAD

**Issue by GreenWolf13** [powercrystals/MineFactoryReloaded#49]
According to this post here: http://forum.feed-the-beast.com/threads/which-mods-do-you-add-to-ultimate.14531/page-7#post-173205

Treecapitator, Steve's Carts Tree Farms, and possibly Forestry Tree Farms, don't work with MFR rubber trees.

**Comment by powercrystals** [comment]
Treecapitator comes with MFR support. Maybe FTB's is old.
I have no plans to ever add support for Steve's Carts or Forestry. If those mods want to, they can.
