### ISSUE TITLE
DSU with 

### ISSUE THREAD

**Issue by ghost** [powercrystals/MineFactoryReloaded#51]
The item forestry.arboriculture.items.ItemGermlingGE (called Apple Oak Sapling in-game)  from Forestry will not stay in a DSU. If you place it in the DSU it is immediately ejected to the nearest inventory or above the DSU if no inventory is available. This happens both if placed manually and if placed via an item routing system like AE.

Picture of item: http://puu.sh/2p6iZ
After inserting in DSU: http://puu.sh/2p6jM

This is running a Big Dig + Additions and using MFR version 2.3.1-281

If you need any more information or want me to try something I'm minchar in #technic, feel free to PM.

**Comment by powercrystals** [comment]
DSUs reject all items with NBT data, which includes all forestry saplings (along with things like potions, enchanted swords, bees, etc). This may change in the future,  but at the moment this is working as intended.
