### ISSUE TITLE
Mod Distribution Request

### ISSUE THREAD

**Issue by GrahamCampbell** [powercrystals/MineFactoryReloaded#52]
Please read the PDF at https://dl.dropbox.com/u/48335821/Modders/Power%20Crystals.pdf regarding permission to use your mod(s).
Any issues opening the document, drop me a note.

Thanks!
Graham Campbell,
Lead Developer At MineUK,
Part Of The MineEU Network.

**Comment by powercrystals** [comment]
Why did you post this and PM me the same request? When you don't even have to ask anyway?

**Comment by GrahamCampbell** [comment]
Sorry. I wasn't sure if you would get the PM.
