### ISSUE TITLE
Error with latest IC2 builds 291-294 due to API change

### ISSUE THREAD

**Issue by fogger** [powercrystals/MineFactoryReloaded#78]
Looks like the machine recipe methods have been removed, and a new Recipe Manager has been added.
[#291 commit: Transition recipe system for basic machines, matter amplifier and scrapbox drops](http://ic2api.player.to:8080/job/IC2_lf/291/changes#detail3)

`Caught exception from MineFactoryReloaded|CompatIC2`

```
java.lang.NoSuchMethodError: ic2.api.Ic2Recipes.addExtractorRecipe(Lnet/minecraft/item/ItemStack;Lnet/minecraft/item/ItemStack;)V
    at powercrystals.minefactoryreloaded.modhelpers.ic2.IC2.load(IC2.java:76)
    ...
```

**Test Setup:**
- minecraftforge-universal-1.5.1-7.7.1.659
- industrialcraft-2_1.115.294-lf
- PowerCrystalsCore-1.1.3B1-84
- MineFactoryReloaded-2.5.0B1-528

**Comment by Emys** [comment]
Should be updated now.
