### ISSUE TITLE
Nomenclature issue

### ISSUE THREAD

**Issue by MFernflower** [powercrystals/MineFactoryReloaded#81]
ComputerCraft already has the name "RedNet" in some of its blocks and items, to avoid confusion, I would recommend renaming your "RedNet" to something else like "GlowWire"

**Comment by CannibalVox** [comment]
The minecraft decompiler already has the name "Fernflower".  To avoid confusion, I would recommend renaming yourself "MPlantbloom".

**Comment by CannibalVox** [comment]
In all seriousness, though, CC does not have any blocks or items with rednet in the name.  Here is the entirety of CC's rednet:

"Before the creation of the in-game wireless networking API, the term "Rednet" referred to a system created by one of the ComputerCraft users based on bundled cables from a popular Minecraft mod - RedPower. It also allowed communication between computers, but the data was transferred slowly - every bit was converted to redstone signal, that lasted about 0,1 seconds. On the release of ComputerCraft 1.3, the system became useless, as the wireless networking was officially implemented to the mod."

Computercraft has a single API that is named "rednet" for historical reasons, and this API exists alongside the following other API's:  colors, coroutine, redstone, string, turtle, os, math, paintutils

I assume that these other API's names are not off limit, correct?

**Comment by MFernflower** [comment]
http://www.sixprizes.com/wp-content/uploads/a_winner_is_you_1024.jpg

**Comment by powercrystals** [comment]
In case anyone else stumbles across this issue, I've had this discussion with cloudy and dan200, so no, you do not need to defend ComputerCraft on their behalf. We agreed that the collision was unfortunate but probably too late to realistically change by the time I was informed of it. Due to CanVox's second post above, there should not be any real confusion to new users.
