### ISSUE TITLE
White signals getting mixed with other colors.

### ISSUE THREAD

**Issue by GSValore** [powercrystals/MineFactoryReloaded#85]
Circuit #1:
Wave (Square) [Timer]
Pd Const 40
I/O Up White

Circuit #2:
Passthrough
I/O South White [In]
I/O Up Orange [out]

When I activate the second circuit with a lever, it behaves a normal.  However, when I turn the signal off, the redstone lamps attached as orange on the up-path flicker on and off at the interval for the square wave generator.

I was able to fix the issue by changing the color bands to magenta on the square wave generator's path.

**Comment by powercrystals** [comment]
I can't reproduce this:
http://i.imgur.com/nJd5Jeq.png

**Comment by GSValore** [comment]
I tried reproducing it in the setup where it occurred; no luck.  I'll consider it a quirk that only happened once.
