### ISSUE TITLE
Harvester with adjacent inventory full still harvests

### ISSUE THREAD

**Issue by CrazyCodeUK** [powercrystals/MineFactoryReloaded#93]
When a harvester is outputting to a chest it will continue to harvest even when no space is in the adjacent inventory. At which point the produce is destroyed instead of stopping the harvester.

**Comment by thatsIch** [comment]
This is probably with all Machines that way for example
- Composter 
- to Fertilizer

Items will spill all over if the Fertilizer has nothing to fertilize anymore.
