### ISSUE TITLE
Natura barley

### ISSUE THREAD

**Issue by CrazyCodeUK** [powercrystals/MineFactoryReloaded#94]
When the planter plants natura barley seeds some times these will become cotton plants.

When the fertilizer applied compost to the barley seeds some times these will become cotton plants.

**Comment by Emys** [comment]
Which build of MFR and version of Natura are you running?

**Comment by CrazyCodeUK** [comment]
Natura_1.5.1_2.0.19
MineFactoryReloaded-2.5.4-665

**Comment by Emys** [comment]
I think I fixed the fertilizer thing, but was unable to reproduce any planter bugs. Reopen the issue if you're still running into it in new builds.
