### ISSUE TITLE
natura cotton

### ISSUE THREAD

**Issue by CrazyCodeUK** [powercrystals/MineFactoryReloaded#95]
The fertilizer will attempt to apply fertilizer to cotton plants continuously at the stage where pink seeds are visible even though it cannot force them to progress any further.

**Comment by Emys** [comment]
Same applies here, which build of MFR and version of Natura are you running?

**Comment by CrazyCodeUK** [comment]
Natura_1.5.1_2.0.19
MineFactoryReloaded-2.5.4-665

**Comment by Emys** [comment]
That is... very strange. I'll see if I can find out what's going on. It -should- be able to make them grow from the pink stage.

**Comment by Emys** [comment]
Should be fixed now.
